### PR TITLE
Feature/deprecate setup android

### PR DESCRIPTION
**Pull request by doerfli**
@msfjarvis: I tried to merge your request into a feature branch, but now i get this error ... can you help me out here. You can also see the link to the ci job below. Thanks. 

```
Warning: Failed to read or create install properties file.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Failed to install the following SDK components:
      build-tools;29.0.3 Android SDK Build-Tools 29.0.3
  The SDK directory is not writable (/usr/local/lib/android/sdk)


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s
##[error]Process completed with exit code 1.
```

### CODE REVIEW

**Comment by msfjarvis** [comment]
GitHub Actions only has build tools 29.0.2 as of now, if you switch your app to that the build should go ahead just fine.

**Comment by doerfli** [comment]
Oh, that was an easy one. Thanks. Is there an overview whats contained in the base image?

**Comment by msfjarvis** [comment]
> Oh, that was an easy one. Thanks. Is there an overview whats contained in the base image?

https://github.com/actions/virtual-environments contains all the code GitHub uses to generate these images.

**Comment by msfjarvis** [comment]
`build-tools;29.0.3` should have been available according to [this](https://github.com/actions/virtual-environments/pull/495) PR, I've pinged them about the discrepancy.

**Comment by doerfli** [comment]
Thanks!

**Pull request merged**
