### PR TITLE
Fix french translation

### PR DESCRIPTION
**Pull request by yoobi**

### CODE REVIEW

**Comment by yoobi** [comment]
Here is the google_play.xml as I didn't know where to add it in the project

[google_play.xml.zip](https://github.com/doerfli/hacked/files/5307689/google_play.xml.zip)

**Comment by doerfli** [comment]
Thanks.

**Comment by doerfli** [comment]
I did a recent update that included three additional strings _action_sort_numpwned_, _action_sort_dateadded_, _action_sort_name_. Would you mind providing translations for those three too? I updated your branch and included them at the end of the file.

**Comment by yoobi** [comment]
Sure, for the `sort by count` what is the count ? Number of time pwned ?

**Comment by doerfli** [comment]
Yes, the number of Times an account has been pwned.

Yo Ob <notifications@github.com> schrieb am So., 4. Okt. 2020, 17:14:

**Pull request merged**
